declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module 'exponential-moving-average'
declare module 'react-dates/lib/theme/DefaultTheme'
declare module 'react-with-styles/lib/ThemedStyleSheet'
